// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"theme-color\" content=\"#4f46e5\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/layout/base.templ`, Line: 10, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - Mercato</title><script src=\"https://unpkg.com/htmx.org@2.0.3\"></script><script src=\"https://unpkg.com/htmx-ext-ws@2.0.1/ws.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script></head><body class=\"bg-[#f8fafc] text-slate-900 flex flex-col min-h-screen font-sans selection:bg-indigo-100 selection:text-indigo-700\"><!-- Subtle Background Decoration --><div class=\"fixed inset-0 -z-10 overflow-hidden pointer-events-none\" aria-hidden=\"true\"><div class=\"absolute -top-[10%] -left-[10%] w-[60%] h-[60%] sm:w-[40%] sm:h-[40%] rounded-full bg-indigo-50/60 blur-[120px]\"></div><div class=\"absolute top-[30%] -right-[10%] w-[50%] h-[50%] sm:w-[30%] sm:h-[30%] rounded-full bg-emerald-50/50 blur-[100px]\"></div></div><!-- Header --><header class=\"bg-white/80 backdrop-blur-md border-b border-slate-200/60 sticky top-0 z-50\"><div class=\"container mx-auto px-4 sm:px-6 h-[60px] flex items-center justify-between\"><a href=\"/\" class=\"flex items-center gap-2 group\" aria-label=\"Mercato home\"><div class=\"bg-indigo-600 p-1.5 rounded-lg shadow-lg shadow-indigo-200/60 group-hover:shadow-indigo-200 transition-shadow\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-4 w-4 text-white\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"3\" d=\"M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z\"></path></svg></div><span class=\"text-lg font-black text-slate-900 tracking-tight\">Mercato</span></a></div></header><!-- Main content --><main class=\"flex-grow container mx-auto px-4 sm:px-6 py-6 sm:py-10\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><!-- Footer --><footer class=\"bg-white border-t border-slate-100 py-8 mt-12\"><div class=\"container mx-auto px-4 sm:px-6 text-center\"><p class=\"text-slate-300 text-xs font-semibold\">&copy; 2026 Mercato. All rights reserved.</p><div class=\"mt-3 flex items-center justify-center gap-2\"><span class=\"h-px w-6 bg-slate-100\"></span><p class=\"text-[10px] font-black text-slate-200 uppercase tracking-widest\">Built with Passion</p><span class=\"h-px w-6 bg-slate-100\"></span></div></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
